### ISSUE TITLE
Map.forEach: arguments passed in wrong order.

### ISSUE THREAD

**Issue by nicksrandall** [d3/d3-arrays#12]
The callback function for `Map.forEach` gets called with 3 arguments (in order) for each item in collection: 

1. Element Value
2. Element Key
3. Map

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach

The `d3.map` gets called with key then value (so backwards).

I understand that you can't rely on browser support for native JavaScript collections (Map and Set) but I think you should mimic their apis as much as possible.

I'm happy to send in a PR with the change if you think such a change should be made.

**Comment by nicksrandall** [comment]
FWIW, I think the spec is wrong and it should be your way. That said, lets follow standards.

**Comment by mbostock** [comment]
Consistency with the standard is good, but there are complicating factors here, namely that d3.map is not a shim for ES6 Map because it’s not really possible to shim ES6 Map. You can get a lot closer than d3.map, but I taking it as far as you can would be counterproductive. Some differences:

* D3’s map coerces keys to strings, whereas ES6 Maps can use any object.
* D3 calls it [map.remove](https://github.com/d3/d3-arrays#map_remove), whereas ES6 says [map.delete](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete).
* D3 lacks a [map.clear](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear) method.
* D3’s map is not [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/%40%40iterator). (There’s not really a way to shim this feature.)
* Likewise, D3’s [map.keys](https://github.com/d3/d3-arrays#map_keys) returns an array, not an iterator.
* Likewise, D3’s [map.values](https://github.com/d3/d3-arrays#map_values) returns an array, not an iterator.
* D3’s [map.entries](https://github.com/d3/d3-arrays#map_entries) method returns an array of {key, value} objects, not an iterator of [key, value].
* D3’s [map.set](https://github.com/d3/d3-arrays#map_set) returns the set value, rather than the map instance
* D3’s [map.size](https://github.com/d3/d3-arrays#map_size) is method, not a [read-only accessor property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/size).
* D3’s [map.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach) doesn’t accept a *thisArg*.
* D3 provides a [map.empty](https://github.com/d3/d3-arrays#map_empty) method.

Until recently, my plan for 4.0 was to remove d3.map and d3.set, adopt ES6 Map and Set, and provide a [barebones shim](https://github.com/d3/d3-bundler/blob/bf2290e2fbcd69b3c70eda0e064d52dd877c8669/src/polyfill/Map.js) for runtimes that lack this native feature. But I decided the polyfill approach was flawed because the shim behaves very differently from the native feature, and this would leak out in D3’s public API (such as [d3.namespaces](https://github.com/d3/d3-selection/blob/master/src/namespaces.js) and [nest.map](https://github.com/d3/d3-arrays#nest_map), which previously used ES6 Map).

I’d love to drop the shim and use ES6 Map and Set directly, but I don’t think it’s appropriate yet to require that of all users. And I don’t believe it’s possible to create a true shim of ES6 collections because that depends on language features like iterators and symbols.

Now, my intention is for d3.map and d3.set to exist on their own independent of ES6: similar, yes, but different. It’s confusing that the forEach method uses the opposite order of arguments from ES6, but d3.map has been around since February 2012, and changing the behavior now would be confusing, too.

So… how about renaming it to map.each and set.each? That’s similar to selection.each, and would make the difference from ES6 more apparent. And, it’s shorter and all lowercase, which I like. :grin:

**Comment by mbostock** [comment]
See #14.

**Comment by mbostock** [comment]
Fixed in 0.2.0.
